name:                heart-core
version:             0.3.1
github:              "ejconlon/heart-core"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2019 Eric Conlon"
category:            Prelude
synopsis:            An opinionated library prelude in the UnliftIO style

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/heart-core#readme>

dependencies:
- base >=4.12 && <5
- aeson >=1.4
- aeson-casing >=0.2
- containers >=0.6
- deepseq >=1.4
- exceptions >=0.10
- filepath >=1.4
- hashable >=1.2
- lens >=4.17
- list-t >=1.0
- mtl >=2.2
- newtype-generics >=0.5
- text >=1.2
- unliftio >=0.2
- unliftio-core >=0.1
- unordered-containers >=0.2

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - NoImplicitPrelude
  - TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src
